### ISSUE TITLE
Inconsistent Default Flag Values

### ISSUE THREAD

**Issue by waymobetta** [ChainSafe/chainbridge-core#144]
There exist default flag values that are not consistent across all CLI commands. Perhaps this is intended, perhaps this is not intended but we should discuss to ensure proper behavior.

An example of when this is believed to be incorrect behavior is when looking at the `--decimals` flag default values. 

For some commands (see examples below), the `--decimals` flag is given the default value of `18` which is standard for the ERC20 spec, while in other cases it is given the default value of `0`, which is neither standard nor probably wanted unless perhaps it is a non-fungible token, in which case it would likely not be an ERC20.

**Examples:** (not comprehensive)
`erc20 deposit`: [0 Decimals](https://github.com/ChainSafe/chainbridge-core/blob/main/chains/evm/cli/erc20/deposit.go#L35)
`erc20 approve`: [18 Decimals](https://github.com/ChainSafe/chainbridge-core/blob/main/chains/evm/cli/erc20/approve.go#L32)
`admin withdraw`: [0 Decimals](https://github.com/ChainSafe/chainbridge-core/blob/main/chains/evm/cli/admin/withdraw.go#L22)

**TODO**:
- [ ] mark all occurrences of `--decimals` as **required**
- [ ] ensure `--decimals` default value is...perhaps remove default value entirely to avoid incorrectly defaulting to 18 (standard) when fewer decimals may be needed
- [ ] perhaps `--threshold` should default to 2, rather than 0 ([shown here](https://github.com/ChainSafe/chainbridge-core/blob/main/chains/evm/cli/admin/set-threshold.go#L16))
- [ ] any bool flags should probably also default to false

## Expected Behavior

Across all CLI commands, the default values should be consistent as long as this is appropriate; otherwise, if there are certain commands where the default values **should** differ, then there should be comments for developers denoting the intentional change.

## Current Behavior

In some cases, the default flag values differ. These should be consistent across all CLI commands

## Possible Solution

We should have a discussion and agree on default values to be used for flags
