### ISSUE TITLE
Confusing/improperly written flag description for admin withdraw + implement CLI command

### ISSUE THREAD

**Issue by waymobetta** [ChainSafe/chainbridge-core#145]
During the port of CLI commands from the [cb-sol-cli](https://github.com/ChainSafe/chainbridge-deploy/blob/main/cb-sol-cli/) to chainbridge-core, some flag descriptions seem to have gotten a bit confusing/improperly worded causing confusion.

In one such example, the `admin withdraw` CLI command in chainbridge-core has two flags that are stated within both of their respective flag descriptions to be mutually exclusive: `--amount` and `--tokenId`, though both of these commands are also denoted as [required](https://github.com/ChainSafe/chainbridge-core/blob/develop/chains/evm/cli/admin/withdraw.go#L24).

This should be discussed to provide proper description going forward.

The below `cb-sol-cli` example is provided to show how flags were previously described when using this legacy tool, specific to the `admin withdraw` command.

**cb-sol-cli examples:**
[admin withdraw](https://github.com/ChainSafe/chainbridge-deploy/blob/main/cb-sol-cli/cmd/admin.js#L113-L126)

#### TODO
- [ ] update flag descriptions to make less confusing
- [ ] remove mutually exclusive flags and/or required flag conflicts
- [x] implement `withdraw` CLI command
- [x] reference changes from [solidity PR](https://github.com/ChainSafe/chainbridge-solidity/pull/416)

## Expected Behavior

Flag descriptions should not be confusing, and if mutually exclusive, then both flags should not be marked as required.

## Current Behavior

Flag descriptions are confusing and are likely to conflict causing incorrect behavior.
